INSERT INTO patients ( 
    nom, 
    nom_ar, 
    prenom, 
    prenom_ar, 
    sexe, pay, 
    nationalite, 
    adresse, 
    cin, 
    ville, 
    province, 
    code_postal, 
    tel, 
    tel_ext, 
    email, 
    photo, 
    accepted_at, 
    accepted, 
    date_naissance ) 
    VALUES ( 
    'John Doe', 
    'جون دو',
    'Jane', 'جين', 
    'M', 'USA', 'USA', 
    '123 Main St', 1234567890, 
    'New York', 'NY', 10001, 1234567890, 123, 
    'john.doe@example.com', 
    'path/to/image.jpg', 
    CURRENT_TIMESTAMP, 0, 
    '1990-01-01' );